

name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  MOBILE_CSPROJ: DemoGitActionXamarin.iOS/DemoGitActionXamarin.iOS.csproj
  IPA_PATH: DemoGitActionXamarin.iOS/bin/iPhone/Release/DemoGitActionXamarin.ipa
  ANDROID_CSPROJ: DemoGitActionXamarin.Android/DemoGitActionXamarin.Android.csproj
jobs:
  build:
    name: android
    runs-on: macos-latest
    steps:
    - name: Publish app to play store
      uses: r0adkll/upload-google-play@v1
      with:
        # serviceAccountJson: DemoGitActionXamarin.Android/bin/key/service_account.json
        serviceAccountJsonPlainText : ${{ secrets.SERVICEACCOUNTJSON }}
        packageName: com.nick
        releaseFile: com.nick.demogitaction.demogitactionxamarin-Signed.aab
        track: internal
